import SessionProvider from '@/Components/SessionProvider'
import './globals.css'
import { Montserrat ,Lato } from 'next/font/google'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'
import Login from '@/Components/Login'
import Sidebar from '@/Components/Sidebar'

const montserrat = Montserrat({ subsets: ['latin'] , variable : '--font-monty' })
const lato = Lato({ weight : ['100'] , subsets: ['latin'] ,variable : '--font-lato' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({children,}: {children: React.ReactNode})
{
  const session = await getServerSession (authOptions)

  return (
    <html lang="en">
      <body className={montserrat.variable}>
        <SessionProvider session={session}>
          {!session ? <Login /> : <div className=' grid lg:grid-cols-4 gap-[60px]  h-screen bg-[#f5f5f5] w-full '>
                <Sidebar />
                {children}
            
            </div>}
        </SessionProvider>
      </body>
    </html>
  )
}
